---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true
  attributes:
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true
    mysql-multi:
      server_version: '5.5'
      server_repl_password: "randompass"
      server_root_password: "randompass"
    postgresql:
      version: '9.3'
      enable_pgdg_apt: true
      enable_pgdg_yum: true
    holland:
      password: "randompass"
    openssh:
      server:
        password_authentication: 'yes'
        permit_root_login: 'yes'
    platformstack:
      iptables:
        allow_ssh_from_world: true

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
    - recipe[build-essential]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
    - recipe[build-essential]
  - name: centos-6.6
    run_list:
    - recipe[yum]
    - recipe[build-essential]

# out of scope for de-dupe effort, and broken too
#  - name: centos-7.0
#    run_list:
#    - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[wrapper::default]

# Can be used as a quick way to test the python bugs on centos 6
# https://github.com/rackspace-cookbooks/stack_commons/issues/85
#
#  - name: python
#    run_list:
#      - recipe[stack_commons::python]
