---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  attributes:
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true
    mysql:
      server_root_password: "randompass"
      server_repl_password: "randompass"
      server_debian_password: "randompass"
    postgresql:
      version: '9.3'
      enable_pgdg_apt: true
      enable_pgdg_yum: true
    holland:
      password: "randompass"
    openssh:
      server:
        password_authentication: 'yes'
        permit_root_login: 'yes'
    platformstack:
      iptables:
        allow_ssh_from_world: true

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: centos-6.5
    run_list:
    - recipe[yum]

# out of scope for de-dupe effort, and broken too
#  - name: centos-7.0
#    run_list:
#    - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[wrapper::default]
